---

#
# Directories
#
      
- name: Ensure exports directory exists
  file: state=directory path="{{ nfsd_exports_dir }}" owner=root group=root mode=0755

- name: Ensure data directory exists for each export
  file: state=directory path="{{ item.path }}" owner=root group=root mode=0755
  with_items: "{{ nfsd_exports }}"

- name: Ensure bind mount directory exists for each export
  file: state=directory path="{{ nfsd_exports_dir }}/{{ item.path | basename }}" owner=root group=root mode=0755
  with_items: "{{ nfsd_exports }}"

#
# Bind mounts
#

# Ansible has a bug with bind-mounted directories, see
# https://github.com/ansible/ansible-modules-core/issues/1942.
#
# So instead of 'state=mounted', we only specify 'state=present' and
# handle mounting via an Ansible registered variable (as mentioned in
# the issue thread above).
- name: Ensure mount point for bind mount directory is defined for each export
  mount: state=present name="{{ nfsd_exports_dir }}/{{ item.path | basename }}" src="{{ item.path }}" fstype="none" opts="bind"
  register: nfsd_fstab_config
  with_items: "{{ nfsd_exports }}"
  
- name: Ensure all mountpoints are mounted
  when: "{{ nfsd_fstab_config.results | selectattr('changed') | list | length }}"
  command: mount -a

#
# Configure /etc/exports
#
- name: Ensure export is defined for each export
  template: src=templates/exports.j2 dest=/etc/exports owner=root group=root mode=0644
  notify: restart nfs
